"""empty message

Revision ID: 389c851d52fc
Revises: b869d7484b8b
Create Date: 2025-11-02 18:13:50.302453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389c851d52fc'
down_revision = 'b869d7484b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
