"""empty message

Revision ID: 6d909ef01d36
Revises: c1c1723c0084
Create Date: 2025-10-31 02:27:52.750692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d909ef01d36'
down_revision = 'c1c1723c0084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('caption',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=320),
               existing_nullable=False)
        batch_op.drop_constraint('post_user_id_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_unique_constraint('post_user_id_key', ['user_id'])
        batch_op.alter_column('caption',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    op.drop_table('follower')
    # ### end Alembic commands ###
